### ISSUE TITLE
Wrong number of arguments in add_access_controls_to_solr_params

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra-head#261]
```
     ArgumentError:
       wrong number of arguments (2 for 1)
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/hydra-access-controls-9.1.4/lib/hydra/access_controls_enforcement.rb:72:in `add_access_controls_to_solr_params'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/lib/blacklight/search_builder.rb:122:in `block (2 levels) in processed_parameters'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/lib/blacklight/search_builder.rb:119:in `each'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/lib/blacklight/search_builder.rb:119:in `block in processed_parameters'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/lib/blacklight/search_builder.rb:118:in `tap'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/lib/blacklight/search_builder.rb:118:in `processed_parameters'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/blacklight-5.13.1/lib/blacklight/search_builder.rb:90:in `to_hash'
```

**Comment by jcoyne** [comment]
This was a problem in worthwhile, I was including AccessControlsEnforcement on a controller instead of the SearchBuilder
