### ISSUE TITLE
Ldp::Gone Error When Deleting Permissions

### ISSUE THREAD

**Issue by jonathandixon** [projecthydra/hydra-head#401]
In a Hyrax application that uses hydra-head 10.4.0 the following error occurs when deleting a permission from a work.

```
Ldp::Gone - :
  ldp (0.6.3) lib/ldp/client/methods.rb:119:in `block in check_for_errors'
  ldp (0.6.3) lib/ldp/client/methods.rb:117:in `check_for_errors'
  ldp (0.6.3) lib/ldp/client/methods.rb:25:in `block in head'
  activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
  ldp (0.6.3) lib/ldp/client/methods.rb:17:in `head'
  /Users/dixonj16/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
  active-fedora (11.1.2) lib/active_fedora/initializing_connection.rb:22:in `head'
  ldp (0.6.3) lib/ldp/resource.rb:59:in `head'
  ldp (0.6.3) lib/ldp/resource.rb:42:in `new?'
  active-fedora (11.1.2) lib/active_fedora/relation/finder_methods.rb:194:in `load_from_fedora'
  active-fedora (11.1.2) lib/active_fedora/relation/finder_methods.rb:181:in `find_one'
  active-fedora (11.1.2) lib/active_fedora/relation/finder_methods.rb:228:in `find_with_ids'
  active-fedora (11.1.2) lib/active_fedora/relation/finder_methods.rb:52:in `find'
  active-fedora (11.1.2) lib/active_fedora/querying.rb:3:in `find'
  active-fedora (11.1.2) lib/active_fedora/associations/basic_contains_association.rb:8:in `block in find_target'
  active-fedora (11.1.2) lib/active_fedora/associations/basic_contains_association.rb:8:in `find_target'
  active-fedora (11.1.2) lib/active_fedora/associations/collection_association.rb:242:in `load_target'
  active-fedora (11.1.2) lib/active_fedora/associations/association.rb:36:in `reload'
  hydra-access-controls (10.4.0) app/models/hydra/access_control.rb:55:in `reset'
  hydra-access-controls (10.4.0) app/models/hydra/access_control.rb:38:in `permissions_attributes='
  hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:21:in `permissions_attributes_without_uniqueness='
  hydra-access-controls (10.4.0) app/models/concerns/hydra/access_controls/permissions.rb:66:in `permissions_attributes='
  active-fedora (11.1.2) lib/active_fedora/attribute_assignment.rb:51:in `_assign_attribute'
  active-fedora (11.1.2) lib/active_fedora/attribute_assignment.rb:45:in `block in _assign_attributes'
  active-fedora (11.1.2) lib/active_fedora/attribute_assignment.rb:44:in `_assign_attributes'
  active-fedora (11.1.2) lib/active_fedora/attribute_assignment.rb:38:in `assign_attributes'
  active-fedora (11.1.2) lib/active_fedora/attribute_assignment.rb:9:in `attributes='
  active-fedora (11.1.2) lib/active_fedora/attributes/serializers.rb:24:in `attributes='
  hyrax/app/actors/hyrax/actors/base_actor.rb:55:in `apply_save_data_to_curation_concern'
  hyrax/app/actors/hyrax/actors/base_actor.rb:20:in `update'
  ...
```

To reproduce run the latest Hyrax test app. Create a work with share permissions. Edit the work and remove a share permission.

This error does not occur when using hydra-head 10.3.0.

**Comment by mjgiarlo** [comment]
I believe @jcoyne is going to take a look at this today. Thanks for reporting this, @jonathandixon

**Comment by jcoyne** [comment]
Here's the trace of where the delete is happening: https://gist.github.com/jcoyne/b3b92630a8957ce68b07e90c2f90fe93

**Comment by jcoyne** [comment]
Permission attributes looked like this:

```
"permissions_attributes"=>{"0"=>{"access"=>"read", "_destroy"=>"true", "id"=>"03e6abb1-572e-4c45-8270-3333f47962f6/32/1a/85/2c/321a852c-6217-427b-938c-ab3887834970"}}
```

**Comment by jcoyne** [comment]
This appears to be a bug in `ActiveFedora::AssociationsBasicContainsAssociation#reload`.  It doesn't clear out the `owner.resource`. It's still using a cached copy here:
https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/associations/basic_contains_association.rb#L5
